version: "3"

services:
  backend:
    container_name: streamysnap_authservice_backend
    image: parinyapt/streamysnap-authservice:v1
    ports:
      - "${BACKEND_PORT}:80"
    networks:
      - default
    environment:
      TZ: Asia/Bangkok
      DATABASE_MYSQL_HOST: db
      DATABASE_MYSQL_DBNAME: ${DB_NAME}
      DATABASE_MYSQL_USERNAME: ${DB_USERNAME}
      DATABASE_MYSQL_PASSWORD: ${DB_PASSWORD}
      DATABASE_TABLE_PREFIX: streamysnap_authservice_
      APP_NAME: StreamySnap Auth Service Production
      APP_BASE_URL: http://auth.prinpt.com
      JWT_SIGN_KEY_AUTHSESSION: production_AUTHSESSION123456789
      JWT_SIGN_KEY_TEMPORARYTOKEN: production_TEMPORARYTOKEN123456789
      JWT_SIGN_KEY_ACCESSTOKEN: production_ACCESSTOKEN123456789
      JWT_SIGN_KEY_REFRESHTOKEN: production_REFRESHTOKEN123456789

  db:
    container_name: streamysnap_authservice_database
    image: mariadb:latest
    restart: always
    networks:
      - default
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    container_name: streamysnap_authservice_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    networks:
      - default
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=256M

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
